name: digito_graph
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cryptography: ^2.7.0
  states_rebuilder: ^6.4.0
  navigation_builder: ^0.0.4
  rename: ^3.0.2
  flutter_native_splash: ^2.4.0
  file_picker: ^8.0.3
  pretty_qr_code: ^3.3.0
  qr_image: ^1.0.0
  path_provider: ^2.1.3
  syncfusion_flutter_pdf: ^25.2.5
  pdfx: ^2.6.0
  image_watermark: ^0.1.0
  share_plus: ^9.0.0
  qr_code_dart_scan: ^0.8.0
  image: ^4.2.0
  uuid: ^4.4.0
  image_picker: ^1.1.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  validators: ^3.0.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher.png"
  min_sdk_android: 21
  # web:
  #   generate: true
  #   image_path: "assets/images/launcher.png"
  #   background_color: "
  #   theme_color: "
  windows:
    generate: true
    image_path: "assets/images/launcher.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - assets/pdf/
